### ISSUE TITLE
Deprecated Error

### ISSUE THREAD

**Issue by coolcat-creations** [JoomTools/plg_content_jtcsv2html#2]
Bei mir kommt ein Fehler in der ansicht: Deprecated: The each() function is deprecated. This message will be suppressed on further calls in .../plugins/content/jtcsv2html/jtcsv2html.php on line 243

:)

**Comment by degobbis** [comment]
Behoben mit der Version [3.99.0](https://github.com/joomtools/plg_content_jtcsv2html/releases/tag/3.99.0)
